services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vira-net

  redis:
    image: redis:7
    restart: unless-stopped
    networks:
      - vira-net

  redpanda:
    image: redpandadata/redpanda:latest
    env_file:
      - .env
    restart: unless-stopped
    container_name: redpanda
    ports:
      - "9092:9092"
      - "9644:9644"
      - "29092:29092" # Добавим внутренний порт для Kafka
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "512M"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9092
    networks:
      - vira-net

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - gateway
    networks:
      - vira-net

  vira-id:
    build: ../services/vira-id
    env_file:
      - .env
    ports:
      - "8081:8080" # внутренний порт сервиса 8080, наружный 8081 для локального доступа
    depends_on:
      - postgres
      - redis
      - redpanda
    networks:
      - vira-net

  vira-events-consumer:
    build: ../services/vira-events-consumer
    env_file:
      - .env
    depends_on:
      - postgres
      - redpanda
    ports:
      - "8085:8085"
    networks:
      - vira-net

  vira-api-wish:
    build: ../services/vira-api-wish
    env_file:
      - .env
    ports:
      - "8082:8080"
    depends_on:
      - redis
      - vira-id
      - postgres
    networks:
      - vira-net

  vira-api-dev:
    build: ../services/vira-api-dev
    env_file:
      - .env
    ports:
      - "8083:8080" # сменил порт внешнего на 8083, внутренний оставил 8080
    depends_on:
      - redis
      - vira-id
      - postgres
    networks:
      - vira-net

  gateway:
    build: ../gateway
    ports:
      - "8080:8080" # API Gateway слушает 8080 внутри и снаружи
    env_file:
      - .env
    depends_on:
      - vira-id
      - vira-api-dev
      - vira-api-wish
    networks:
      - vira-net

  vira-dev:
    build: ../frontend/vira-dev
    ports:
      - "5173:5173"
    networks:
      - vira-net
    depends_on:
      - gateway

  vira-wish:
    build: ../frontend/vira-wish
    ports:
      - "5174:5174"
    networks:
      - vira-net
    depends_on:
      - gateway

volumes:
  pgdata:


networks:
  vira-net:
